### ISSUE TITLE
Only secure origins are allowed

### ISSUE THREAD

**Issue by atimon** [rejas/MMM-MotionDetector#16]
When I run the module I get the following errors in the console log:

> diff-cam-engine.js:106 [Deprecation] getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

> MMM-MotionDetector.js:77 MMM-MotionDetector: DiffCamEngine init failed. NotSupportedError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

**Comment by rejas** [comment]
Yeah, thats a known limitation of getUserMedia that is already documented in the README. Are you running your MM software with a custom address in the config?
