### ISSUE TITLE
can this module send our a custom notification?

### ISSUE THREAD

**Issue by dxfan227** [rejas/MMM-MotionDetector#18]
Was hoping to sync this with another module to refresh upon wake/motion

**Comment by rejas** [comment]
Its already sending notifications, cant you handle those in our other modules?

**Comment by dxfan227** [comment]
probably. I don't know any coding what so ever. what notification does the module broad cast when it detects motion?

**Comment by rejas** [comment]
When detected its sends MOTION_DETECTED and DEACTIVATE_MONITOR if the monitor gets back to sleep

**Comment by dxfan227** [comment]
@rejas  thanks...i'll see if I can use this. 

unfortuantly after I closed the other issue thread I went to my mirror and mmm-motion detector was not active again.. I manally sent the screen on command via terminal and when the screen loaded magic mirror was still running, so this time there was something strange about the module crashing or something. I'll keep an eye on it, in the mean time is there any good way to check a log when something like this happens? something that would give me info from hours ago.
