### ISSUE TITLE
Testing results

### ISSUE THREAD

**Issue by BrianHepler** [rejas/MMM-MotionDetector#31]
First, thank you for the module!
Second, I just tested this on a RPi4 4GB and the RpiCam. Worked great. I had to fiddle around with the address & IP whitelist, but I got it working without having to do the proxy thing.

I second the request to customize the notification send on motion detection.

**Comment by rejas** [comment]
Hey @BrianHepler I added an option to never disable the monitor (by setting the timeout to -1). Could you check if that stills sends the notification and therefor would help you?

**Comment by BrianHepler** [comment]
I'll check it out in the next day or so. Thank you!

**Comment by BrianHepler** [comment]
Let's combine the new features into the other issue. Easier to track.
