### ISSUE TITLE
Multi-Camera issue

### ISSUE THREAD

**Issue by camaro4life18** [rejas/MMM-MotionDetector#47]
I have 2 camera's connected to my Pi, another app is using one of the cams, which MotionDetector keeps trying to use and fails with error...
NotReadableError: could not start video source

**Comment by camaro4life18** [comment]
As usual, I got impatient and solved my own problem by changing the code to be this...
 navigator.mediaDevices
      .getUserMedia({ video: { deviceId: "video0"} })
Basically had to hard code it to pick a specific camera. If I get time I may put in a pull request to add this as a config option. The weird behavior however, is It acts like it is using both cams now for motion detection.

**Comment by rejas** [comment]
Hi @camaro4life18 I also got impatient and crated a PR with the option to specify the deviceId. Can you give it a try and report back if it helps you?
