### ISSUE TITLE
Old node_helper.js

### ISSUE THREAD

**Issue by adbeem** [rejas/MMM-MotionDetector#5]
Hi rejas, after doing some google and trying countless of methods, there was one guy mentioning using the default driver. So would you mind sharing me the old node_helper.js? I think the default driver lasts longer than a bit. Sorry for bothering you too much btw i love this module but can't seem to work pretty well for me

**Comment by rejas** [comment]
Not sure why you would need the old node_helper.js. The current version should support all graphicsdrivers with its new vcgencmd implementation. 
Also you can browse in the history of the file to the old version: https://github.com/rejas/MMM-MotionDetector/commits/master/node_helper.js
